### ISSUE TITLE
Make templates localizable

### ISSUE THREAD

**Issue by twanvl** [twanvl/MagicSetEditor2#100]
Currently locale specific translations for field names, insert symbol menu, etc. are in the locale file. But the locale is really a program level file, and it can't easily be extended by template makers.

Instead, these translations should be in the templates themselves. Something like:
```
insert symbol menu:
	item:
		name: T
		label:
			en_US: Tap symbol
			fr_FR: Symbol du tap
```
and
```
set field:
	type: symbol
	name: symbol
	label:
		nl_NL: Symbool
	description:
		en_US: The symbol for this set, double click to edit
		es_ES: El símbolo de este conjunto, haga doble clic para editar
```

This should be fairly straightforward to implement. The only thing is backwards compatibility, since suddenly something like a `description` can be either a single string, or a mapping from locale to strings. The simplest solution to this problem is to name the localized variant something else, like `localized_description`.

**Comment by CajunAvenger** [comment]
This looks good, and yea I agree having something like `localized_description` that MSE checks first, then falls back to just `description` if its not there would be great to avoid needing everyone to update a dozen or more mana files (or all their files if this gets extended to stylesheet option descriptions)
