### ISSUE TITLE
Assertion error:

### ISSUE THREAD

**Issue by BigCasper** [twanvl/MagicSetEditor2#109]
![image](https://user-images.githubusercontent.com/39709276/95133789-22fb0e00-0762-11eb-83b3-4163659baaa9.png)
No good idea what's happening, but its evidently the savefile, since all other work fine (for now).
Version 2.0.1 I guess.

**Comment by twanvl** [comment]
I recommend switching to a newer version. The latest is 2.1.2, and lots of bugs have been fixed.

**Comment by BigCasper** [comment]
> I recommend switching to a newer version. The latest is 2.1.2, and lots of bugs have been fixed.

Where is the download? I searched all over and can't find one.

**Comment by fenhl** [comment]
<https://github.com/twanvl/MagicSetEditor2/releases/tag/v2.1.2>
