### ISSUE TITLE
v2.0.2-rc1 Unusable buttoms no longer gray out

### ISSUE THREAD

**Issue by CajunAvenger** [twanvl/MagicSetEditor2#13]
On 2.0.1, buttons that were unable to be clicked were grayed out, on 2.0.2 they keep the same image. They still can't be clicked, it's just a visual issue. It's most notable on the Save button (at least due to the save bug from before) where it becomes unclear if the set's actually been saved.
[Image on startup, 2.0.1 on top, 2.0.2 on bottom](https://cdn.discordapp.com/attachments/443557716842250240/705399150899888230/unknown.png)

**Comment by twanvl** [comment]
Probably due to changes in wxWidgets' automatic generation of grayed out toolbar icons. I'll see if I can generate these in mse.
