### ISSUE TITLE
v2.0.2-rc1 - magicseteditor.exe is missing .dlls

### ISSUE THREAD

**Issue by CajunAvenger** [twanvl/MagicSetEditor2#2]
I tried to test the magicseteditor.exe and was met with the error message "The program can't start because wxmsw313u_core_vc_custom.dll is missing from your computer." instead. @fenhl mentioned getting 4 errors but I don't have the names on those.

**Comment by twanvl** [comment]
I have added the .dll files, I'll look into static linking for the future.

**Comment by CajunAvenger** [comment]
Thank you, it is working now.
