### ISSUE TITLE
Getting blank cards and dictionary errors for inscrutable reasons

### ISSUE THREAD

**Issue by halian** [twanvl/MagicSetEditor2#25]
When attempting to open a set file made with MSE 2.0.1 in MSE 2.0.2 (using commit `1c351838390255e307f22e3840a5ed3bfc760c8b`) on Arch Linux, no cards render for me, and I get a panoply of errors complaining about the lack of an `en_us` dictionary, even though I have all the same templates (mainly Mainframe 2020) and dictionaries installed as I did with 2.0.1. Please advise?

**Comment by twanvl** [comment]
The dictionary errors happen because the magic template looks for `magic-words.en_us.dic`, but the file is named `magic-words.en_US.dic`

**Comment by twanvl** [comment]
Renaming the file fixes this issue.
