### ISSUE TITLE
2.0.2-rc4 Quick search, - operator no longer works, "!" can't be searched as the beginning of a string

### ISSUE THREAD

**Issue by CajunAvenger** [twanvl/MagicSetEditor2#43]
In what looks like may have been intended but unmarked change (?), `-text` is no longer a negated search and `!text` is. However the negation is overriding the "" operators, so `"!text"` is searching for cards without `text` and not cards with `!text`, where on 2.0.1 `"-text"` does look for cards with `-text`

**Comment by twanvl** [comment]
I fixed the quote issue, now `"!text"` searches for the literal exclamation mark.

Question: do you think should `!` or `-` be used for negation? It wasn't really an intentional change.

**Comment by fenhl** [comment]
I think `-` is better because of precedent from other search engines.
