### ISSUE TITLE
Linux: Hotkeys do not work within textboxes

### ISSUE THREAD

**Issue by halian** [twanvl/MagicSetEditor2#53]
When running MSE (using commit 83448a16672c11547d2f94e310edbb9a742b059a) in Arch Linux, hotkeys only work if focus is not in a textbox.

**Comment by twanvl** [comment]
What hotkeys do you mean? In what text box (it might matter)?

**Comment by halian** [comment]
Any hotkeys and any textbox (including text fields on a card).

**Comment by halian** [comment]
Also, some hotkeys (e.g. Ctrl-Enter) don't work at all, regardless of where focus is.
