### ISSUE TITLE
2.0.2-rc8 Using field.layout in template scripts gives "nothing has no member" errors on startup.

### ISSUE THREAD

**Issue by CajunAvenger** [twanvl/MagicSetEditor2#56]
The initial code:
`bar_equation := {card_style.text.top + 0.5*(card_style.text.layout.blocks[0].bottom+card_style.text.layout.blocks[1].top)}`

When opening MSE for the first time, the console gives the error:
```
nothing has no member 'blocks'
in function bar_equation
while updating styles for 'flavor_bar'
```

If you open more files with the same client open, the error does not occur, but it does reoccur if you reload, It doesn't appear to be affecting any cards, just firing an unnecessary error.

Currently it can be worked around by using an 'or else' check.
`bar_equation := {if card_style.text.layout.blocks[0].bottom or else 0 > 0 then card_style.text.top + 0.5*(card_style.text.layout.blocks[0].bottom+card_style.text.layout.blocks[1].top) else 600}`

**Comment by twanvl** [comment]
Currently when the text hasn't been laid out yet `card_style.text.layout` is `nil`. It would probably be more convenient to have default values in there instead..
