### ISSUE TITLE
2.0.2-rc8 field.layout.separators is giving incorrect data

### ISSUE THREAD

**Issue by CajunAvenger** [twanvl/MagicSetEditor2#57]
The numbers given by card_style.field.layout.separators are half-and-a-bit off from the actual value, which is correct from taking the average of the two card_style.layout.blocks coordinates. From running a bunch of cards, most of the separator values are 0.5*(separator)±7, (most of them with ±3). I haven't been able to determine a solid pattern in what's causing the additional fluctuations, other than shrink-overflow having a larger effect. (eg, four cards with 3 lines in block[0] and 3 lines in block[1], the differences were 0.5s - 0.15 for two cards with 14p font, 0.5s + 3.25 for a card with 13p font, and 0.5s + 5.375 for 12p font.)

**Comment by twanvl** [comment]
Do you mean that `separators[0] is not equal to (blocks[0].bottom+blocks[1].top)/2`?

**Comment by CajunAvenger** [comment]
> 
> 
> Do you mean that `separators[0] is not equal to (blocks[0].bottom+blocks[1].top)/2`?

Yes, it is equal to (blocks[0].bottom+blocks[1].top)/4` plus or minus some small number that is variable on font size and probably other values.

**Comment by twanvl** [comment]
Oops, it was `(blocks[0].bottom+blocks[0].top)/2`.

Fixed.
