### ISSUE TITLE
2.0.2-rc8 (Bug/Missing Doc) include file: from other packages saves package location

### ISSUE THREAD

**Issue by CajunAvenger** [twanvl/MagicSetEditor2#63]
There are some older templates that use `include file` to break up their own style code, formatted such as this:

```
# Load scripts for image box
include file: /magic-default-image.mse-include/scripts
# Load font profiles
include file: font_new
```
on 2.0.2-rc8, this is now causing the second include file to attempt to load `/magic-default-image.mse-include/font_new` rather than `font_new` from within the folder.

Switching the order loads everything fine so this might be an intended thing but it should probably get documented if so.

**Comment by twanvl** [comment]
This is a bug.
Is this happening with a top-level `include file`, or inside a script?

**Comment by CajunAvenger** [comment]
It's happening in the `init script:` section of the stylesheet and game files.
