### ISSUE TITLE
Searching "rarity:common" doesn't filter any cards

### ISSUE THREAD

**Issue by CajunAvenger** [twanvl/MagicSetEditor2#66]
Using the `rarity:common` search pulls up all cards in the set, regardless of rarity. This doesn't occur for any of the other rarities, `card.rarity` in the console pulls up the correct rarity, and searchstrings `"common ", "common,", " common", ",common"` all return nothing.

The card field code is below, changing the initial value doesn't change the behavior which seems to be the only time common is by itself.
```
card field:
	type: choice
	name: rarity
	choice: basic land
	choice: common
	choice: uncommon
	choice: rare
	choice: mythic rare
	choice: special
	choice: masterpiece
	initial: common
	card list visible: true
	card list column: 7
	description: The rarity of the card, to edit the symbol switch to the 'set info' tab
	show statistics: false
	icon: stats/rarity.png
	position hint: 100
	choice colors:
		basic land: rgb(109,62,39)
		common:     rgb(33,33,33)
		uncommon:   rgb(224,224,224)
		mythic rare: rgb(202, 49, 35)
		rare:       rgb(255,207,52)
		special:    rgb(190,0,255)
```

**Comment by twanvl** [comment]
There is a `rarity 3` field that is initialized to `common`. The search `field:query` also searches in the field names, so `rarity:..` matches on the `rarity 3` field.

**Comment by CajunAvenger** [comment]
Sure enough. That's only used by one rarely used template so think that can get shuffled back to an extra card field or maybe a style field to fix this.
