### ISSUE TITLE
"Variant" keywords now getting both reminders (add optional keyword parameters?)

### ISSUE THREAD

**Issue by CajunAvenger** [twanvl/MagicSetEditor2#70]
With Dominaria, 'variant' keywords such as "Hexproof from <color>" and "Equip legendary creature <cost>" were added, which did not play nicely with current keyword system, requiring a second keyword with parameter workarounds to accommodate both mechanics, such as
```
Equi<atom-param>p</atom-param> <atom-param>name</atom-param> <atom-param>cost</atom-param>
```
After the keyword changes in 2.1.0, these are now getting both reminder texts for the original and the variant.

A possible fix for this could be having a more in-built variant system that allows for optional parameters, or secondary checks for a keyword if the first doesn't match? Either of these would also provide a fix for the smaller trouble of needing two keywords for some action words, such as the new "mill" keyword needing a "mill X cards" and a "mills X cards" keyword.

**Comment by twanvl** [comment]
Keywords are matched top to bottom, so if "Hexproof from" is defined before "Hexproof", then it will match first. Maybe that can help here? Or are you saying that if you do that you get two copies of reminder text?

I agree that variants might make sense, or perhaps just optional words? So you could have something like `Equip <atom-param-optional>name</atom-param-optional> <atom-param>cost</atom-param>`  or `<choice>mill|mills</choice>`. For mill it might make sense to have it just write `mill(s) <atom-param>number</atom-param> card(s)`.

**Comment by CajunAvenger** [comment]
"Hexproof from" is listed first in the keyword file, and on 2.0.0 it does only give that reminder text, but on 2.1.0 it is adding the reminder text for Hexproof from and normal hexproof, [Image](https://cdn.discordapp.com/attachments/354683158526033921/719691962738933760/unknown.png)
```
keyword:
	keyword: Hexproof from
	match: Hexproo<atom-param>name</atom-param> from <atom-param>name</atom-param>
	mode: core
	reminder: This {if has_pt() then "creature" else "permanent"} can't be the target of {param2} spells or abilities your opponents control.
keyword:
	keyword: Hexproof
	match: Hexproof
	mode: core
	reminder: This { if has_pt() then "creature" else "permanent"} can't be the target of spells or abilities your opponents control.
```

For mill and similar keywords an ability for `(s)` would do well, yeah. Either of -optional or choice looks good, hopefully the optional tag would be able to account for the extra space when the option isn't used?
