### ISSUE TITLE
Mana Symbol Menu Items no longer using names from locale

### ISSUE THREAD

**Issue by CajunAvenger** [twanvl/MagicSetEditor2#84]
In the en.mse-locale file, names for symbols are defined which appear in the menu on 2.0.0, but not in 2.1.1. [Image, 2.0.0 on left, 2.1.1 on right](https://cdn.discordapp.com/attachments/443557716842250240/745883911791444009/unknown.png)

snippit from locale
```
		menu item T:			&Tap symbol	 T
		menu item Q:			&Untap symbol	 Q
		menu item W:			&White mana	 W
		menu item U:			Bl&ue mana	 U
```

**Comment by twanvl** [comment]
The fact that template specific localization is done via the locale is a problem in any case.
A much neater approach will be to move everything to the symbol-font file. See #100.
