### ISSUE TITLE
2.1.1 Potential crash when opening old files or deleting text

### ISSUE THREAD

**Issue by CajunAvenger** [twanvl/MagicSetEditor2#88]
I'm not 100% on the causes so I'll walk through what happened instead:

1) On 2.0.0, all the rules text for a card was deleted.
2) Invisibly, this made the rules text saved for this card to be `</SOFT-LINE></SOFT-LINE><soft-line><soft-line>`
3) Trying to open this set file on 2.1.1 crashes MSE.
4) Copy-pasting this card into 2.1.1 causes the client to lag, but does eventually paste it.
5) Deleting this card or editing the set file to remove the backwards softline tags causes it to stop crashing.

Found an older version of the file, the original rules text was this:
```
<kw-A><nospellcheck>Extract <param-number>6</param-number></nospellcheck><atom-reminder-custom> <i-auto>(As you cast this spell, you may pay up to <param-number>6</param-number> life.)</i-auto></atom-reminder-custom></kw-A>
		<soft-line><soft-line>Counter target spell unless its controller pays <sym-auto>X</sym-auto>, where X is the amount of life this spell e</SOFT-LINE></SOFT-LINE>xtracted.
```
I'm not sure why there are two softlines or why they closing tags are capitalized, but it does open in 2.1.1. However, deleting this text in 2.1.1 causes the program to crash, so it seems whatever is causing the tags to reverse is still around.

**Comment by CajunAvenger** [comment]
Similar bug was found today where a card had empty `<sym></sym><sym></sym>` tags, worked fine in 2.0.0, crashed when opened in 2.1.1, fixed when removed. Going to add a step to the text filter to remove empty `<sym>`s and see if i can't get something to unreverse tags working that way.

**Comment by CajunAvenger** [comment]
> Similar bug was found today where a card had empty `<sym></sym><sym></sym>` tags
A few minutes into that and this looks like at least a partial cause of #90, the formatting buttons are adding the empty tags, which MSE then crashes because of. Unsure of how they keyboard shortcuts come into play there.

**Comment by twanvl** [comment]
The crash was caused by the same problem as #90
