### ISSUE TITLE
2.1.1 Frame color isn't picked automatically based on casting cost

### ISSUE THREAD

**Issue by sepro** [twanvl/MagicSetEditor2#92]
While in 2.0.0 the frame would change automatically once the casting cost was entered, this no longer is the case in 2.1.1. While you can manually specify the color, then the identity dot pops up which would need to be disabled manually as well resulting in a few extra steps per card. 

![Annotation 2020-09-08 093112](https://user-images.githubusercontent.com/6548964/92446482-2b3d4900-f1b6-11ea-9a11-98176e2a517b.png)
When entering the casting cost (in the m15 template), the frame is no longer set automatically to the matching color.

**Comment by CajunAvenger** [comment]
This is caused by not having magic.mse-game updated for version 2.1.0, My updates to that can be found [here](https://github.com/CajunAvenger/Cajun-Style-Templates) if you're not sure where to go for that.

**Comment by sepro** [comment]
Awesome, thanks for those ! This indeed solved the issue
